---
title: <center>교육통계를 활용한 데이터 분석 방법</center>
subtitle: <right>Part 1 시계열 분석 방법</right>
author: 이기준^[국가교육통계연구본부장, standard@kedi.re.kr]
institution: 한국교육개발원
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# 시계열 데이터

-   우리는 연도별 학생수, 날짜별 기온 변화 등과 같이 시간의 흐름에 따라 수집된 데이터를 흔히 볼 수 있다. 특히 가장 흔하게 볼 수 있는 시계열 데이터는 주식시장에서 볼 수 있는데 주식에 관련된 대부분의 데이터가 시계열 데이터이다. 시계열 데이터는 과거의 데이터 패턴을 분석하여 유사한 데이터 흐름이 지속된다는 가정하에 미래 특정한 기간동안의 데이터 흐름을 분석하기 위해 사용되고 있다.

-   시계열 데이터는 일련의 시간간의 흐름에 따라 기록되는 데이터들의 집합이기 때문에 인접한 시간의 데이터간의 상관관계가 존재한다. 최근 우리나라는 저출산 고령화 사회에 접어들었다고 한다. 우리나라의 출생아수는 지속적으로 줄고 있다고 하는데 갑자기 늘거나 갑자기 줄거나 하지는 않는다. 이와 같이 과거의 데이터가 현재의 데이터에 영향을 주는 경향을 자기상관이라고 하는데 비시계열 데이터에 비교해서 이 자기 상관성이 시계열 데이터의 큰 특징이라고 할 수 있다.

-   최근 머신러닝이 발달함에 따라 데이터를 기반으로 예측하는 알고리즘들이 많이 소개되고 사용되고 있다. 그 알고리즘들은 regression, classification, segmentation 등의 알고리즘을 사용하여 모델을 생성하고 새로운 데이터가 주어졌을때 해당 모델을 통해 예측 값을 산출해내는 작업을 수행한다. 그러나 시계열 데이터는 앞서 설명한 자기 상관과 같은 특수성으로 인해 일반적으로 머신러닝에서 사용하는 알고리즘들을 사용하지 않고 시계열 데이터를 분석하기 위한 Arima, Exponential Smoothing 등의 방법을 사용하여 데이터를 모델링 한 후 특별한 입력값이 없어도 미래 시간의 흐름에 따라 일련의 예측값을 생성할 수 있다는 점에서 머신러닝 알고리즘과 차이가 있다.

## 정의

-   시계열(Time Series) 데이터는 일정한 시간에 따른 순차적 정보량을 기록한 데이터임

-   기록되는 순차적 정보량은 여러 측정치가 가능한데 대부분의 경우 가격, 온도, 인구수 등 수치적 측정치로 기록되는 경우가 많음

-   시계열 데이터는 과거 데이터의 흐름에 따른 경향성(Trend), 계절별이나 특정 기간의 경과에 따른 데이터의 반복적 흐름(Seasonality)를 발견하여 향후 불확실한 미래의 데이터 흐름을 예측(Forecasting)하는데 활용함

## 특성

-   고정된 시간 독립변수

    -   일반적으로 데이터 분석시에는 독립변수와 종속변수간의 관계를 분석하는 것이 목적인 경우가 많음
    -   종속변수의 행동을 예측하기 위해서는 하나 혹은 여러개의 독립변수가 필요하고 이들간의 관계성을 도출함으로서 향후 독립변수에 따라 종속변수의 예측값을 도출하게 됨
    -   아래의 예제와 같이 자동차의 속도와 제동거리간에는 그래프 상으로 양의 상관관계를 보이고 있음. 이 예제에서는 제동거리를 종속변수로, 자동차 속도를 독립변수로 분석하였음
    -   그러나 **시계열 데이터의 독립변수 중 하나는 시간으로 고정됨**. 따라서 시계열 데이터는 타 변수와의 상관관계 없이도 자신 스스로 종속변수이자 독립변수로 분석될 수 있음
    -   시계열 데이터를 구축하는데 중요한 요소는 시간 간격이 동일해야 한다는 점임. 예를 들어 매시간, 매일, 매월, 매분기, 매년 등 간격이 일정해야 시계열 데이터를 다루기 위한 다양한 함수들에 적용이 가능함. 다만 간격이 일정하더라도 결측치에 의해 모든 간격의 데이터가 기록되지 않은 데이터에 대해 시계열 데이터를 만들고 그래프를 그릴 수는 있으나 예측에 적용하기 위해서는 일정한 간격의 데이터를 갖추는 것이 더 효과적임

### 자기 상관관계

-   시계열 데이터는 과거의 자기 자신의 데이터와의 상관관계가 존재하는 성질임
-   일반적으로 상관관계는 서로 다른 두개의 변수간의 영향성을 살펴보지만 자기 상관관계는 자기 자신의 n차 지연(lag) 데이터(현재보다 n번째 과거 데이터)와 현재 데이터간의 상관관계가 발생함을 의미함

### 추세 경향성(Trend)

-   시계열 데이터는 장기적으로 점차 증가하거나 점차 감소하는 추세에 대한 경향성을 보이는 경우가 있음
-   추세 경향성은 시간의 흐름에 따라 나타나는 인구, 경기, 기술, 환경 등의 변화에 따라 영향을 받는 데이터의 중장기적인 지속적 데이터의 변동을 말함
-   추세 경향성은 시간축에 따라 발생하는 데이터 변동에 대한 그래프에서 확인이 가능한데 이 변동성을 선형회귀로 단정하여 예측하지 않도록 주의해야함
-   추세 경향성을 선형회귀로 분석할 때는 앞서 언급한 자기 상관관계가 있는지를 먼저 확인한 후에 적용해야 하며 자기 상관관계가 있는 경우에는 선형회귀보다 다른 시계열 분석방법을 활용하는 방법을 고민해야함

### 계절성(Seasonality), 순환성(Cyclic)

-   시계열 데이터는 중장기적인 추세경향성외에 데이터가 달력(Calender)상의 날짜나 기간에 따라 주기적으로 변화하거나 장기적인 시간의 흐름에 따라 오르거나 내리는 추세가 반복되는 변동성을 가지는 경우가 있음
-   계절성은 봄, 여름, 가을, 겨울과 같은 계절, 일, 주, 월, 분기와 같은 기간의 변화에 따라 주기적으로 변동하는 시계열 성질을 말함
-   순환성은 일정한 기간의 특징없이 데이터의 변동성이 반복되거나 1년을 넘겨 주기적으로 발생하는 데이터의 반복성을 말함
-   계절성과 순환성은 혼동되는 경우가 많음. 계절성은 주기가 고정된 기간에 대한 순환성이고 순환성은 변동적 기간에 대한 순환성이고 일반적으로 순환성의 주기가 계절성 주기보다 길기 때문에 계절성은 언제쯤 데이터 피크(Peak)가 나타날지 예측이 가능하나 순환성은 데이터 피크에 대한 예측이 어려운 성질이 있음
-   순환성과 계절성에 대한 구분, 장기 추세경향성과 장기 순환성과의 구분은 어려울 수 있음

### 불확실성(Uncertainty)

-   시계열 모델의 해석에는 반드시 불확실성에 대한 고려가 수반되어야 함. 시계열 분석을 통해 예측된 미래 데이터는 사용된 모델에 적합한 확률 분포 모델(Probability Distribution)을 통한 신뢰구간이 같이 제공되어 평가되어야 함.
-   대부분의 시계열 모델은 불확실성을 표현하기 위한 신뢰구간의 산출이 가능한데 시계열 예측은 예측 기간이 길수록 예측의 신뢰구간이 점점 넓어지게 됨.
